In [7]:
# Cải tiến 1
#Xây dựng n-1 phần từ  có dạng a(1)(n)
import numpy as np
#MA TRAN SO SANH
matrix = np.array([[1, 3 , 1/2, 2 ],
                  [0 , 1,  0,  0],
                  [0, 0,   1,  0],
                  [0, 0,   0,  1]]);
print(matrix); 
print("gia tri: ",matrix[0,0])
print(matrix.shape[0])

[[1.  3.  0.5 2. ]
 [0.  1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]
gia tri:  1.0
4


In [38]:
matrix_2 = np.copy(matrix);
row,col = matrix_2.shape;

for i in range (0, row):
    for j in range(0, col):
        if (i!=j):
            matrix_2[j,i] = 1/matrix_2[i,j]
            
        
print(matrix_2);

[[1.         3.         0.5        2.        ]
 [0.33333333 1.         0.         0.        ]
 [2.                inf 1.         0.        ]
 [0.5               inf        inf 1.        ]]


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  import sys


In [39]:
#matrix_2 = np.copy(matrix);
#row,col = matrix_2.shape;
for i in range (1, row-1):
    for j in range(2, col):
        matrix_2[i,j] = 1/matrix_2[j,i];
        matrix_2[i,j] = matrix_2[i,0] * matrix_2[0,j];
print(matrix_2);
        
        
        

[[1.         3.         0.5        2.        ]
 [0.33333333 1.         0.16666667 0.66666667]
 [2.                inf 1.         4.        ]
 [0.5               inf        inf 1.        ]]


In [40]:
for i in range (0, row):
    for j in range(0, col):
        if (i!=j):
            matrix_2[j,i] = 1/matrix_2[i,j]
            
        
print(matrix_2);

[[1.         3.         0.5        2.        ]
 [0.33333333 1.         0.16666667 0.66666667]
 [2.         6.         1.         4.        ]
 [0.5        1.5        0.25       1.        ]]


In [41]:
#Cải tiến 2
#Xây dựng n-1 phần từ  có dạng a(1)(n)
#MA TRAN SO SANH
matrix = np.array([[1, 3 , 0, 0 ],
                  [0 , 1,  1/6,  0],
                  [0, 0,   1,  4],
                  [0, 0,   0,  1]]);
print(matrix)

[[1.         3.         0.         0.        ]
 [0.         1.         0.16666667 0.        ]
 [0.         0.         1.         4.        ]
 [0.         0.         0.         1.        ]]


In [46]:
matrix_2 = np.copy(matrix);
row,col = matrix_2.shape
for i in range(0,row):
    for j in range (0, col):
        if(matrix_2[i,j]==0 and i<j-1):
            matrix_2[i,j] = 1/ matrix[j,i];
            matrix_2[i,j] = matrix_2[i,j-1]*matrix_2[j-1,j]
print(matrix_2);

[[1.         3.         0.5        2.        ]
 [0.         1.         0.16666667 0.66666667]
 [0.         0.         1.         4.        ]
 [0.         0.         0.         1.        ]]


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in double_scalars
  


In [47]:
for i in range (0, row):
    for j in range(0, col):
        if (i!=j):
            matrix_2[j,i] = 1/matrix_2[i,j]
            
        
print(matrix_2);

[[1.         3.         0.5        2.        ]
 [0.33333333 1.         0.16666667 0.66666667]
 [2.         6.         1.         4.        ]
 [0.5        1.5        0.25       1.        ]]
